server.port: ${SERVER_PORT:0}

spring:
  application:
    name: API-GATEWAY
  profiles:
    active: ${PROFILES:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  cloud:
    config:
      fail-fast: true
  config:
    import: configserver:http://localhost:8787

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, env
  endpoint:
    env:
      show-values: always
