server:
  port: 8090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: Course-Service
          uri: lb://COURSE-SERVICE
          predicates:
            - "Path=/api/courses/**"
          filters:
            - JwtValidationFilter

        - id: University-Service
          uri: lb://UNIVERSITY-SERVICE
          predicates:
             - "Path=/api/universities/**"
          filters:
            - JwtValidationFilter

        - id: Education-Service
          uri: lb://EDUCATION-SERVICE
          predicates:
            - "Path=/api/education/**"
          filters:
            - JwtValidationFilter

        - id: Authentication-Service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - "Path=/api/auth/**"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
logging:
  level:
    root: info
    org.andarworld.apigateway: debug
